version: '2.1'
services:
    worker:
        image: puckel/docker-airflow:1.10.9
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        restart: always
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            - ./config/worker/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./script/entrypoint.sh:/entrypoint.sh
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=${MASTER_VM_HOST}
            - POSTGRES_PORT=5432
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_HOST=${MASTER_VM_HOST}
            - REDIS_PORT=6379
            - REDIS_PASSWORD=redispass
            - APP_SERVER_HOST=${APP_SERVER_HOST}
        command: worker
