version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        command: redis-server --requirepass redispass
        ports:
            - "6379:6379"

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        #volumes:
        #    - pg_data_airflow:/var/lib/postgresql/data/pgdata

    webserver:
        image: puckel/docker-airflow:1.10.9
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - APP_SERVER_HOST=${APP_SERVER_HOST}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            - ./config/master/airflow.cfg:/usr/local/airflow/airflow.cfg 
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
        image: puckel/docker-airflow:1.10.9
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            - ./config/master/airflow.cfg:/usr/local/airflow/airflow.cfg 
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - APP_SERVER_HOST=${APP_SERVER_HOST}
        command: scheduler
#    flower:
#        image: puckel/docker-airflow:1.10.9
#        restart: always
#        depends_on:
#            - redis
#        environment:
#            - REDIS_PASSWORD=redispass
#        ports:
#            - "5555:5555"
#        volumes:
#            - ./dags:/usr/local/airflow/dags
#            - ./requirements.txt:/requirements.txt
#            - ./config/master/airflow.cfg:/usr/local/airflow/airflow.cfg 
#        #command: flower
#        command: ["flower", "--broker=redis://localhost:6379/1", "--port=5555"]  


#    flower:  
#      image: mher/flower
#      environment:
#        - CELERY_BROKER_URL=redis://localhost:6379/1
#        - FLOWER_PORT=5555
#      ports:  
#        - 5555:5555

#volumes: 
#    pg_data_airflow:
#        external: true
